import unittest
from exceptions import UserWarning


class instrospect_dataTest(unittest.TestCase):
    def test_all(self, ):
        raise UserWarning("We apologise for the fault in ... not implemented test ... Those responsible have been sacked")